name: Update Results

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *" # updates daily at 3am

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json
      - run: bun install
      - run: bun run ./scripts/update-results/run.ts
        env:
          GAMES_API_URL: ${{ secrets.GAMES_API_URL }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
